---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [21]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)


In [22]:
df

№ Summer  01 !  02 !  03 !  \
Afghanistan (AFG)                                   13     0     0     2   
Algeria (ALG)                                       12     5     2     8   
Argentina (ARG)                                     23    18    24    28   
Armenia (ARM)                                        5     1     2     9   
Australasia (ANZ) [ANZ]                              2     3     4     5   
Australia (AUS) [AUS] [Z]                           25   139   152   177   
Austria (AUT)                                       26    18    33    35   
Azerbaijan (AZE)                                     5     6     5    15   
Bahamas (BAH)                                       15     5     2     5   
Bahrain (BRN)                                        8     0     0     1   
Barbados (BAR) [BAR]                                11     0     0     1   
Belarus (BLR)                                        5    12    24    39   
Belgium (BEL)                                       25    37    52    53   
Bermuda (BER)                                       17     0     0     1   
Bohemia (BOH) [BOH] [Z]                              3     0     1     3   
Botswana (BOT)                                       9     0     1     0   
Brazil (BRA)                                        21    23    30    55   
British West Indies (BWI) [BWI]                      1     0     0     2   
Bulgaria (BUL) [H]                                  19    51    85    78   
Burundi (BDI)                                        5     1     0     0   
Cameroon (CMR)                                      13     3     1     1   
Canada (CAN)                                        25    59    99   121   
Chile (CHI) [I]                                     22     2     7     4   
China (CHN) [CHN]                                    9   201   146   126   
Colombia (COL)                                      18     2     6    11   
Costa Rica (CRC)                                    14     1     1     2   
Ivory Coast (CIV) [CIV]                             12     0     1     0   
Croatia (CRO)                                        6     6     7    10   
Cuba (CUB) [Z]                                      19    72    67    70   
Cyprus (CYP)                                         9     0     1     0   
...                                                ...   ...   ...   ...   
Sri Lanka (SRI) [SRI]                               16     0     2     0   
Sudan (SUD)                                         11     0     1     0   
Suriname (SUR) [E]                                  11     1     0     1   
Sweden (SWE) [Z]                                    26   143   164   176   
Switzerland (SUI)                                   27    47    73    65   
Syria (SYR)                                         12     1     1     1   
Chinese Taipei (TPE) [TPE] [TPE2]                   13     2     7    12   
Tajikistan (TJK)                                     5     0     1     2   
Tanzania (TAN) [TAN]                                12     0     2     0   
Thailand (THA)                                      15     7     6    11   
Togo (TOG)                                           9     0     0     1   
Tonga (TGA)                                          8     0     1     0   
Trinidad and Tobago (TRI) [TRI]                     16     2     5    11   
Tunisia (TUN)                                       13     3     3     4   
Turkey (TUR)                                        21    39    25    24   
Uganda (UGA)                                        14     2     3     2   
Ukraine (UKR)                                        5    33    27    55   
United Arab Emirates (UAE)                           8     1     0     0   
United States (USA) [P] [Q] [R] [Z]                 26   976   757   666   
Uruguay (URU)                                       20     2     2     6   
Uzbekistan (UZB)                                     5     5     5    10   
Venezuela (VEN)   

In [23]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

df.columns

Index(['# Summer', 'Gold', 'Silver', 'Bronze', 'Total', '# Winter', 'Gold.1',
       'Silver.1', 'Bronze.1', 'Total.1', '# Games', 'Gold.2', 'Silver.2',
       'Bronze.2', 'Combined total'],
      dtype='object')

In [24]:
names_ids = df.index.str.split('\s\(') # split the index by '('
names_ids

Index([                           ['Afghanistan', 'AFG)'],
                                      ['Algeria', 'ALG)'],
                                    ['Argentina', 'ARG)'],
                                      ['Armenia', 'ARM)'],
                            ['Australasia', 'ANZ) [ANZ]'],
                          ['Australia', 'AUS) [AUS] [Z]'],
                                      ['Austria', 'AUT)'],
                                   ['Azerbaijan', 'AZE)'],
                                      ['Bahamas', 'BAH)'],
                                      ['Bahrain', 'BRN)'],
       ...
                                   ['Uzbekistan', 'UZB)'],
                                    ['Venezuela', 'VEN)'],
                                      ['Vietnam', 'VIE)'],
                               ['Virgin Islands', 'ISV)'],
                             ['Yugoslavia', 'YUG) [YUG]'],
       ['Independent Olympic Participants', 'IOP) [IOP]'],
                                 ['Zambia', '

In [25]:
type(names_ids)

pandas.core.indexes.base.Index

In [26]:
df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, Afghanistan to Totals
Data columns (total 16 columns):
# Summer          147 non-null int64
Gold              147 non-null int64
Silver            147 non-null int64
Bronze            147 non-null int64
Total             147 non-null int64
# Winter          147 non-null int64
Gold.1            147 non-null int64
Silver.1          147 non-null int64
Bronze.1          147 non-null int64
Total.1           147 non-null int64
# Games           147 non-null int64
Gold.2            147 non-null int64
Silver.2          147 non-null int64
Bronze.2          147 non-null int64
Combined total    147 non-null int64
ID                146 non-null object
dtypes: int64(15), object(1)
memory usage: 19.5+ KB


In [27]:
df.drop('Totals',inplace=True)


### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [28]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [29]:
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

In [30]:
def answer_one():
    return df.Gold.idxmax()
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [31]:
def answer_two():
    diff = df['Gold'] - df['Gold.1']
    return diff.idxmax()
answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [32]:
def answer_three():
    total = df['Gold'] + df['Gold.1']
    data = df[total > 0]
    rediff = (data['Gold'] - data['Gold.1'])/(data['Gold'] + data['Gold.1'])
    return rediff.idxmax()
answer_three()

'Algeria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [41]:
def answer_four():
    points = df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']
    return points.rename('Points')
answer_four()

Afghanistan                            2
Algeria                               27
Argentina                            130
Armenia                               16
Australasia                           22
Australia                            923
Austria                              569
Azerbaijan                            43
Bahamas                               24
Bahrain                                1
Barbados                               1
Belarus                              154
Belgium                              276
Bermuda                                1
Bohemia                                5
Botswana                               2
Brazil                               184
British West Indies                    2
Bulgaria                             411
Burundi                                3
Cameroon                              12
Canada                               846
Chile                                 24
China                               1120
Colombia        

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [34]:
census_df = pd.read_csv('census.csv')
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [35]:
def answer_five():
    data = census_df[census_df.SUMLEV==50]
    return data.groupby('STNAME')['CTYNAME'].count().idxmax()

answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [55]:
def answer_six():
    data = census_df[census_df.SUMLEV==50]
    three_counties = data.groupby('STNAME')['CENSUS2010POP'].nlargest(3).reset_index()
    return list(three_counties.groupby('STNAME')['CENSUS2010POP'].sum().nlargest(3).index)
answer_six()

['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [37]:
def answer_seven():
    data = census_df.loc[:,'POPESTIMATE2010':'POPESTIMATE2015']
    ind = (data.max(axis=1)-data.min(axis=1)).idxmax()
    return census_df.loc[ind,'CTYNAME']
answer_seven()

'Texas'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [38]:
census_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3193 entries, 0 to 3192
Data columns (total 100 columns):
SUMLEV                   3193 non-null int64
REGION                   3193 non-null int64
DIVISION                 3193 non-null int64
STATE                    3193 non-null int64
COUNTY                   3193 non-null int64
STNAME                   3193 non-null object
CTYNAME                  3193 non-null object
CENSUS2010POP            3193 non-null int64
ESTIMATESBASE2010        3193 non-null int64
POPESTIMATE2010          3193 non-null int64
POPESTIMATE2011          3193 non-null int64
POPESTIMATE2012          3193 non-null int64
POPESTIMATE2013          3193 non-null int64
POPESTIMATE2014          3193 non-null int64
POPESTIMATE2015          3193 non-null int64
NPOPCHG_2010             3193 non-null int64
NPOPCHG_2011             3193 non-null int64
NPOPCHG_2012             3193 non-null int64
NPOPCHG_2013             3193 non-null int64
NPOPCHG_2014             3193 non-n

In [40]:
def answer_eight():
    mask = (census_df['REGION'].isin([1,2]))&(census_df['CTYNAME'].str.startswith('Washington'))&(census_df['POPESTIMATE2015']>census_df['POPESTIMATE2014'])
    return census_df.loc[mask,['STNAME','CTYNAME']]
answer_eight()

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County